const S_STATE='llamacmd_state_v1',S_LOGS='llamacmd_logs_v1';
const $=id=>document.getElementById(id);
const q=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const sh=s=>`'${String(s).replace(/'/g,`'\\''`)}'`;
const filled=v=>v!==undefined&&v!==null&&String(v).trim()!=='';
const opts={yesNo:[['','Unset'],['yes','Emit enabled flag'],['no','Emit disabled flag']],onOff:[['','Unset'],['on','on'],['off','off']],auto:[['','Unset'],['auto','auto'],['on','on'],['off','off']],cache:[['','Unset'],['f32','f32'],['f16','f16'],['bf16','bf16'],['q8_0','q8_0'],['q4_0','q4_0'],['q4_1','q4_1'],['iq4_nl','iq4_nl'],['q5_0','q5_0'],['q5_1','q5_1']]};

// Field catalogue
const SECTIONS=[
{id:'core',title:'Core model source',open:1,summary:'Pick one model source. Local GGUF wins if you fill more than one, because ambiguity is how command lines become haunted.',fields:[
['serverPath','Server executable','text',null,{m:['server'],d:'./llama.cpp/build/bin/llama-server'}],
['cliPath','CLI executable','text',null,{m:['cli'],d:'./llama.cpp/build/bin/llama-cli'}],
['modelPath','Model path','text','-m',{p:'/models/model.gguf',special:1}],
['hfRepo','Hugging Face repo','text','-hf',{p:'ggml-org/model-GGUF:Q4_K_M',special:1}],
['hfFile','HF file','text','-hff',{p:'model-q4_k_m.gguf',special:1}],
['hfToken','HF token','text','-hft',{p:'not saved',secret:1,special:1}],
['modelUrl','Model URL','text','-mu',{p:'https://...',special:1}],
['dockerRepo','Docker model repo','text','-dr',{p:'ai/model:quant',special:1}],
['alias','Server alias','text','-a',{m:['server']}],
['tags','Server tags','text','--tags',{m:['server']}],
['mmproj','MMProj path','text','-mm',{}],
['mmprojUrl','MMProj URL','text','-mmu',{}],
['mmprojAuto','MMProj auto','select',null,{o:opts.yesNo,map:{yes:'--mmproj-auto',no:'--no-mmproj'}}],
['mmprojOffload','MMProj offload','select',null,{o:opts.yesNo,map:{yes:'--mmproj-offload',no:'--no-mmproj-offload'}}],
['talkerModel','Talker model','text','-tk',{m:['server']}],
['code2wavModel','Code2WAV model','text','-c2w',{m:['server']}]
]},
{id:'runtime',title:'Runtime and context',open:1,summary:'Core execution knobs. Empty fields do not emit flags.',fields:[
['ctxSize','Context size','number','-c',{raw:1,p:'65536'}],['predict','Predict tokens','number','-n',{raw:1,p:'-1'}],['batchSize','Batch size','number','-b',{raw:1,p:'2048'}],['ubatchSize','Ubatch size','number','-ub',{raw:1,p:'512'}],['threads','Threads','number','-t',{raw:1}],['threadsBatch','Threads batch','number','-tb',{raw:1}],['seed','Seed','number','-s',{raw:1,p:'-1'}],['keep','Keep tokens','number','--keep',{raw:1}],['prio','Thread priority','select','--prio',{raw:1,o:[['','Unset'],['-1','Low'],['0','Normal'],['1','Medium'],['2','High'],['3','Realtime']]}],['numa','NUMA mode','select','--numa',{raw:1,o:[['','Unset'],['distribute','distribute'],['isolate','isolate'],['numactl','numactl']]}],['cpuMask','CPU mask','text','--cpu-mask',{raw:1}],['cpuRange','CPU range','text','--cpu-range',{raw:1,p:'0-15'}],['cpuStrict','CPU strict','select','--cpu-strict',{raw:1,o:[['','Unset'],['0','0'],['1','1']]}],['cpuMaskBatch','CPU mask batch','text','--cpu-mask-batch',{raw:1}],['cpuRangeBatch','CPU range batch','text','--cpu-range-batch',{raw:1}],['cpuStrictBatch','CPU strict batch','select','--cpu-strict-batch',{raw:1,o:[['','Unset'],['0','0'],['1','1']]}],['swaFull','Full SWA cache','checkbox','--swa-full',{}],['noWarmup','Disable warmup','checkbox','--no-warmup',{}],['escapeMode','Escape sequences','select',null,{o:opts.yesNo,map:{yes:'--escape',no:'--no-escape'}}],['perfMode','Internal perf timings','select',null,{o:opts.yesNo,map:{yes:'--perf',no:'--no-perf'}}],['spmInfill','SPM infill','checkbox','--spm-infill',{}]
]},
{id:'gpu',title:'GPU, devices, and offload',open:1,summary:'No fit prediction. Choose the flags, run the benchmark, and log the real numbers.',fields:[
['device','Device list','text','-dev',{raw:1,p:'0,1'}],['listDevices','List devices and exit','checkbox','--list-devices',{}],['gpuLayers','GPU layers','text','-ngl',{raw:1,p:'auto, all, or number'}],['splitMode','Split mode','select','-sm',{raw:1,o:[['','Unset'],['none','none'],['layer','layer'],['row','row'],['tensor','tensor']]}],['tensorSplit','Tensor split','text','-ts',{raw:1,p:'3,1'}],['mainGpu','Main GPU','number','-mg',{raw:1}],['flashAttn','Flash attention','select','-fa',{raw:1,o:opts.auto}],['fit','Fit mode','select','-fit',{raw:1,o:opts.onOff}],['fitTarget','Fit target MiB','text','-fitt',{raw:1,p:'1024 or 1024,2048'}],['fitCtx','Fit ctx minimum','number','-fitc',{raw:1}],['kvOffload','KV offload','select',null,{o:opts.yesNo,map:{yes:'-kvo',no:'-nkvo'}}],['repack','Weight repack','select',null,{o:opts.yesNo,map:{yes:'--repack',no:'-nr'}}],['noHost','Bypass host buffer','checkbox','--no-host',{}],['opOffload','Operation offload','select',null,{o:opts.yesNo,map:{yes:'--op-offload',no:'--no-op-offload'}}],['cpuMoe','Keep all MoE weights on CPU','checkbox','-cmoe',{}],['nCpuMoe','MoE CPU layers','number','-ncmoe',{raw:1}],['overrideTensor','Override tensor','text','-ot',{p:'blk.*.ffn_.*=CPU'}],['overrideKv','Override metadata KV','text','--override-kv',{p:'tokenizer.ggml.add_bos_token=bool:false'}],['checkTensors','Check tensors','checkbox','--check-tensors',{}]
]},
{id:'memory',title:'Memory, cache, and shifting',summary:'KV cache, mmap, mlock, prompt cache, slot cache, and context-shift controls.',fields:[
['cacheTypeK','Cache type K','select','-ctk',{raw:1,o:opts.cache}],['cacheTypeV','Cache type V','select','-ctv',{raw:1,o:opts.cache}],['defragThold','Defrag threshold','number','-dt',{raw:1}],['mlock','MLock','checkbox','--mlock',{}],['mmap','MMap','select',null,{o:opts.yesNo,map:{yes:'--mmap',no:'--no-mmap'}}],['directIo','Direct IO','select',null,{o:opts.yesNo,map:{yes:'-dio',no:'-ndio'}}],['contextShift','Context shift','select',null,{o:opts.yesNo,map:{yes:'--context-shift',no:'--no-context-shift'}}],['promptCache','Prompt cache file','text','--prompt-cache',{m:['cli']}],['promptCacheAll','Prompt cache all','checkbox','--prompt-cache-all',{m:['cli']}],['promptCacheRo','Prompt cache read-only','checkbox','--prompt-cache-ro',{m:['cli']}],['cachePrompt','Server prompt cache','select',null,{m:['server'],o:opts.yesNo,map:{yes:'--cache-prompt',no:'--no-cache-prompt'}}],['cacheReuse','Cache reuse chunk','number','--cache-reuse',{m:['server'],raw:1}],['lookupCacheStatic','Static lookup cache','text','-lcs',{m:['server']}],['lookupCacheDynamic','Dynamic lookup cache','text','-lcd',{m:['server']}],['cacheRam','Cache RAM MiB','number','-cram',{m:['server'],raw:1}],['kvUnified','Unified KV','select',null,{m:['server'],o:opts.yesNo,map:{yes:'-kvu',no:'-no-kvu'}}],['cacheIdleSlots','Cache idle slots','select',null,{m:['server'],o:opts.yesNo,map:{yes:'--cache-idle-slots',no:'--no-cache-idle-slots'}}],['slotSavePath','Slot save path','text','--slot-save-path',{m:['server']}]
]},
{id:'sampling',title:'Sampling and constraints',summary:'Sampler order, classic sampling, DRY, XTC, adaptive-p, dynamic temperature, grammar, JSON schema, and logit bias.',fields:[
['samplers','Samplers','text','--samplers',{p:'penalties;dry;top_k;typ_p;top_p;min_p;xtc;temperature'}],['samplerSeq','Sampler sequence','text','--sampler-seq',{raw:1,p:'edskypmxt'}],['ignoreEos','Ignore EOS','checkbox','--ignore-eos',{}],['temp','Temperature','number','--temp',{raw:1,step:'0.01'}],['topK','Top K','number','--top-k',{raw:1}],['topP','Top P','number','--top-p',{raw:1,step:'0.01'}],['minP','Min P','number','--min-p',{raw:1,step:'0.01'}],['topNSigma','Top N Sigma','number','--top-n-sigma',{raw:1,step:'0.01'}],['xtcProbability','XTC probability','number','--xtc-probability',{raw:1,step:'0.01'}],['xtcThreshold','XTC threshold','number','--xtc-threshold',{raw:1,step:'0.01'}],['typicalP','Typical P','number','--typical-p',{raw:1,step:'0.01'}],['repeatLastN','Repeat last N','number','--repeat-last-n',{raw:1}],['repeatPenalty','Repeat penalty','number','--repeat-penalty',{raw:1,step:'0.01'}],['presencePenalty','Presence penalty','number','--presence-penalty',{raw:1,step:'0.01'}],['frequencyPenalty','Frequency penalty','number','--frequency-penalty',{raw:1,step:'0.01'}],['dryMultiplier','DRY multiplier','number','--dry-multiplier',{raw:1,step:'0.01'}],['dryBase','DRY base','number','--dry-base',{raw:1,step:'0.01'}],['dryAllowedLength','DRY allowed length','number','--dry-allowed-length',{raw:1}],['dryPenaltyLastN','DRY penalty last N','number','--dry-penalty-last-n',{raw:1}],['drySequenceBreaker','DRY sequence breaker','text','--dry-sequence-breaker',{}],['adaptiveTarget','Adaptive target','number','--adaptive-target',{raw:1,step:'0.01'}],['adaptiveDecay','Adaptive decay','number','--adaptive-decay',{raw:1,step:'0.01'}],['dynatempRange','Dynatemp range','number','--dynatemp-range',{raw:1,step:'0.01'}],['dynatempExp','Dynatemp exp','number','--dynatemp-exp',{raw:1,step:'0.01'}],['mirostat','Mirostat','select','--mirostat',{raw:1,o:[['','Unset'],['0','0 disabled'],['1','1'],['2','2']]}],['mirostatLr','Mirostat LR','number','--mirostat-lr',{raw:1,step:'0.01'}],['mirostatEnt','Mirostat entropy','number','--mirostat-ent',{raw:1,step:'0.01'}],['logitBias','Logit bias','text','-l',{raw:1,p:'15043+1'}],['grammar','Grammar','textarea','--grammar',{wide:1}],['grammarFile','Grammar file','text','--grammar-file',{}],['jsonSchema','JSON schema','textarea','-j',{wide:1}],['jsonSchemaFile','JSON schema file','text','-jf',{}],['backendSampling','Backend sampling','checkbox','-bs',{}]
]},
{id:'chat',title:'Prompt, chat, and reasoning',summary:'CLI prompt controls and shared chat template controls. Server mode mostly uses API request bodies.',fields:[
['prompt','Prompt','textarea','-p',{m:['cli'],wide:1}],['promptFile','Prompt file','text','-f',{m:['cli']}],['systemPrompt','System prompt','textarea','-sys',{m:['cli'],wide:1}],['conversation','Conversation mode','checkbox','-cnv',{m:['cli']}],['singleTurn','Single turn','checkbox','--single-turn',{m:['cli']}],['interactive','Interactive','checkbox','-i',{m:['cli']}],['reversePrompt','Reverse prompt','text','-r',{}],['special','Special token output','checkbox','-sp',{}],['jinja','Jinja','select',null,{o:opts.yesNo,map:{yes:'--jinja',no:'--no-jinja'}}],['chatTemplate','Chat template','text','--chat-template',{p:'chatml, llama3, gemma, qwen...'}],['chatTemplateFile','Chat template file','text','--chat-template-file',{}],['chatTemplateKwargs','Chat template kwargs','textarea','--chat-template-kwargs',{m:['server'],wide:1}],['skipChatParsing','Skip chat parsing','select',null,{m:['server'],o:opts.yesNo,map:{yes:'--skip-chat-parsing',no:'--no-skip-chat-parsing'}}],['prefillAssistant','Prefill assistant','select',null,{m:['server'],o:opts.yesNo,map:{yes:'--prefill-assistant',no:'--no-prefill-assistant'}}],['reasoning','Reasoning','select','-rea',{raw:1,o:opts.auto}],['reasoningFormat','Reasoning format','select','--reasoning-format',{m:['server'],raw:1,o:[['','Unset'],['none','none'],['deepseek','deepseek'],['deepseek-legacy','deepseek-legacy'],['auto','auto']]}],['reasoningBudget','Reasoning budget','number','--reasoning-budget',{raw:1}],['reasoningBudgetMessage','Reasoning budget message','text','--reasoning-budget-message',{}]
]},
{id:'server',title:'Server-only API controls',open:1,m:['server'],summary:'Networking, endpoints, batching, router mode, UI, metrics, and API behavior.',fields:[
['host','Host','text','--host',{d:'0.0.0.0',raw:1,m:['server']}],['port','Port','number','--port',{d:'8080',raw:1,m:['server']}],['apiKey','API key','text','--api-key',{p:'not saved',secret:1,m:['server']}],['apiKeyFile','API key file','text','--api-key-file',{m:['server']}],['apiPrefix','API prefix','text','--api-prefix',{raw:1,m:['server']}],['timeout','Timeout seconds','number','-to',{raw:1,m:['server']}],['threadsHttp','HTTP threads','number','--threads-http',{raw:1,m:['server']}],['parallel','Parallel slots','number','-np',{raw:1,m:['server']}],['contBatching','Continuous batching','select',null,{m:['server'],o:opts.yesNo,map:{yes:'-cb',no:'-nocb'}}],['ui','Web UI','select',null,{m:['server'],o:opts.yesNo,map:{yes:'--ui',no:'--no-ui'}}],['uiConfig','UI config JSON','textarea','--ui-config',{m:['server'],wide:1}],['uiConfigFile','UI config file','text','--ui-config-file',{m:['server']}],['embedding','Embeddings only','checkbox','--embedding',{m:['server']}],['rerank','Reranking endpoint','checkbox','--rerank',{m:['server']}],['pooling','Pooling','select','--pooling',{raw:1,m:['server'],o:[['','Unset'],['none','none'],['mean','mean'],['cls','cls'],['last','last'],['rank','rank']]}],['metrics','Metrics endpoint','checkbox','--metrics',{m:['server']}],['props','Props endpoint','checkbox','--props',{m:['server']}],['slots','Slots endpoint','select',null,{m:['server'],o:opts.yesNo,map:{yes:'--slots',no:'--no-slots'}}],['sslKeyFile','SSL key file','text','--ssl-key-file',{m:['server']}],['sslCertFile','SSL cert file','text','--ssl-cert-file',{m:['server']}],['mediaPath','Media path','text','--media-path',{m:['server']}],['modelsDir','Router models dir','text','--models-dir',{m:['server']}],['modelsPreset','Router models preset','text','--models-preset',{m:['server']}],['modelsMax','Router models max','number','--models-max',{raw:1,m:['server']}],['modelsAutoload','Router autoload','select',null,{m:['server'],o:opts.yesNo,map:{yes:'--models-autoload',no:'--no-models-autoload'}}],['tools','Built-in tools','text','--tools',{raw:1,p:'read_file,grep_search or all',m:['server']}],['sleepIdleSeconds','Sleep idle seconds','number','--sleep-idle-seconds',{raw:1,m:['server']}]
]},
{id:'speculative',title:'Speculative decoding, MTP, and ngram draft',summary:'Native MTP, classic draft models, and ngram speculative controls. The raw MTPS box exists because upstream is moving fast.',fields:[
['dflashModel','DFlash model path','text',null,{p:'/models/model-DFlash.gguf'}],['specType','Spec type','text','--spec-type',{raw:1,p:'draft-mtp or draft-simple,ngram-cache'}],['specDefault','Default speculative config','checkbox','--spec-default',{}],['specDraftModel','Draft model path','text','-md',{}],['specDraftHf','Draft HF repo','text','-hfd',{}],['specDraftDevice','Draft device list','text','-devd',{raw:1}],['specDraftGpuLayers','Draft GPU layers','text','-ngld',{raw:1,p:'auto, all, or number'}],['specDraftThreads','Draft threads','number','-td',{raw:1}],['specDraftThreadsBatch','Draft threads batch','number','-tbd',{raw:1}],['specDraftCpuMoe','Draft CPU MoE','checkbox','-cmoed',{}],['specDraftNCpuMoe','Draft MoE CPU layers','number','-ncmoed',{raw:1}],['specDraftNMax','Draft tokens max','number','--spec-draft-n-max',{raw:1}],['specDraftNMin','Draft tokens min','number','--spec-draft-n-min',{raw:1}],['specDraftPSplit','Draft split probability','number','--spec-draft-p-split',{raw:1,step:'0.01'}],['specDraftPMin','Draft minimum probability','number','--spec-draft-p-min',{raw:1,step:'0.01'}],['specDraftBackendSampling','Draft backend sampling','select',null,{o:opts.yesNo,map:{yes:'--spec-draft-backend-sampling',no:'--no-spec-draft-backend-sampling'}}],['specNgramModNMin','Ngram mod min','number','--spec-ngram-mod-n-min',{raw:1}],['specNgramModNMax','Ngram mod max','number','--spec-ngram-mod-n-max',{raw:1}],['specNgramModNMatch','Ngram mod match','number','--spec-ngram-mod-n-match',{raw:1}],['specNgramSimpleSizeN','Ngram simple size N','number','--spec-ngram-simple-size-n',{raw:1}],['specNgramSimpleSizeM','Ngram simple size M','number','--spec-ngram-simple-size-m',{raw:1}],['specNgramSimpleMinHits','Ngram simple min hits','number','--spec-ngram-simple-min-hits',{raw:1}],['mtpRawFlags','Raw MTPS flags','textarea',null,{wide:1,p:'--some-new-mtp-flag value',special:1}]
]},
{id:'adapters',title:'Adapters and control vectors',summary:'LoRA, scaled LoRA, control vectors, and layer ranges.',fields:[
['lora','LoRA path(s)','text','--lora',{}],['loraScaled','Scaled LoRA','text','--lora-scaled',{p:'adapter.gguf:0.8'}],['loraInitWithoutApply','LoRA init without apply','checkbox','--lora-init-without-apply',{m:['server']}],['controlVector','Control vector','text','--control-vector',{}],['controlVectorScaled','Scaled control vector','text','--control-vector-scaled',{p:'vector.gguf:0.6'}],['controlVectorLayerRange','Control vector layer range','text','--control-vector-layer-range',{raw:1,p:'8 31'}]
]},
{id:'output',title:'Output, logging, and raw passthrough',summary:'The safety valve. New upstream flag? Paste it here and move on with your life.',fields:[
['verbose','Verbose','checkbox','-v',{m:['cli']}],['logDisable','Disable logs','checkbox','--log-disable',{}],['logFile','Log file','text','--log-file',{}],['noDisplayPrompt','No display prompt','checkbox','--no-display-prompt',{m:['cli']}],['showTimings','Show timings','select',null,{m:['cli'],o:opts.yesNo,map:{yes:'--show-timings',no:'--no-show-timings'}}],['completionBash','Bash completion and exit','checkbox','--completion-bash',{}],['version','Version and exit','checkbox','--version',{}],['extraFlags','Extra flags appended verbatim','textarea',null,{wide:1,p:'--flag value\\n--another-flag',special:1}]
]}];

const F=()=>SECTIONS.flatMap(s=>s.fields.map(a=>({id:a[0],label:a[1],type:a[2],flag:a[3],...(a[4]||{})})));
const mode=()=>q('input[name="mode"]:checked')?.value||'server';
const applies=(x,m)=>!x.m||x.m.includes(m);
function renderBuilder(){builderMount.innerHTML=SECTIONS.map(s=>`<details class="flag-section" data-modes="${s.m?s.m.join(','):'all'}"${s.open?' open':''}><summary>${esc(s.title)}</summary><div class="section-body"><p class="section-summary">${esc(s.summary||'')}</p><div class="input-grid">${s.fields.map(renderField).join('')}</div></div></details>`).join('')}
function renderField(a){let f={id:a[0],label:a[1],type:a[2],flag:a[3],...(a[4]||{})},m=f.m?f.m.join(','):'all',wide=f.wide||f.type==='textarea'?' wide':'',help=f.help?`<p class="field-help">${esc(f.help)}</p>`:'',ph=f.p?` placeholder="${esc(f.p)}"`:'',val=f.d??'';if(f.type==='checkbox')return `<div class="input-group${wide}" data-modes="${m}"><div class="checkbox-field"><input type="checkbox" id="${f.id}" data-key="${f.id}"><div><label for="${f.id}">${esc(f.label)}</label>${help}</div></div></div>`;if(f.type==='select')return `<div class="input-group${wide}" data-modes="${m}"><label for="${f.id}">${esc(f.label)}</label><select id="${f.id}" data-key="${f.id}">${(f.o||[['','Unset']]).map(([v,l])=>`<option value="${esc(v)}"${String(val)===String(v)?' selected':''}>${esc(l)}</option>`).join('')}</select>${help}</div>`;if(f.type==='textarea')return `<div class="input-group${wide}" data-modes="${m}"><label for="${f.id}">${esc(f.label)}</label><textarea id="${f.id}" data-key="${f.id}" rows="4"${ph}>${esc(val)}</textarea>${help}</div>`;return `<div class="input-group${wide}" data-modes="${m}"><label for="${f.id}">${esc(f.label)}</label><input type="${f.type||'text'}" id="${f.id}" data-key="${f.id}" value="${esc(val)}"${ph}${f.step?` step="${esc(f.step)}"`:''}>${help}</div>`}
function state(){let s={mode:mode(),multiline:multilineCheck.checked};F().forEach(f=>{let e=$(f.id);if(e)s[f.id]=f.type==='checkbox'?e.checked:e.value});return s}
function saveState(){let s=state();F().forEach(f=>{if(f.secret)delete s[f.id]});localStorage.setItem(S_STATE,JSON.stringify(s))}
function loadState(){try{return JSON.parse(localStorage.getItem(S_STATE))||{}}catch{return {}}}
function applyState(){let s=loadState();if(s.mode){let r=q(`input[name="mode"][value="${String(s.mode).replace(/["\\]/g,'\\$&')}"]`);if(r)r.checked=true}if(s.multiline!==undefined)multilineCheck.checked=!!s.multiline;F().forEach(f=>{let e=$(f.id);if(e&&s[f.id]!==undefined)f.type==='checkbox'?e.checked=!!s[f.id]:e.value=s[f.id]})}
function updateVisibility(){let m=mode();document.querySelectorAll('[data-modes]').forEach(e=>{let v=e.getAttribute('data-modes');e.classList.toggle('hidden',!(v==='all'||v.split(',').includes(m)))})}
function addEvents(){document.querySelectorAll('[data-key]').forEach(e=>{e.addEventListener('input',updateAll);e.addEventListener('change',updateAll)});document.querySelectorAll('input[name="mode"]').forEach(e=>e.addEventListener('change',updateAll));multilineCheck.addEventListener('change',updateAll);copyCommandBtn.onclick=()=>copyText(build().cmd,'Command copied.');resetBuilderBtn.onclick=resetBuilder;clearLogsBtn.onclick=clearLogs;parseTimingBtn.onclick=parseTimingIntoLogFields;logRunBtn.onclick=logRun;copyMarkdownBtn.onclick=()=>copyText(logsMarkdown(),'Markdown copied.');copyCsvBtn.onclick=()=>copyText(logsCsv(),'CSV copied.')}
function updateAll(){updateVisibility();let b=build();commandOutput.textContent=b.cmd;commandModeLabel.textContent=mode()==='server'?'llama-server':'llama-cli';warningList.innerHTML=b.warn.map(w=>`<div class="warning-item">${esc(w)}</div>`).join('');saveState()}
function build(){let s=state(),m=s.mode,parts=[],warn=[],bin=m==='server'?(s.serverPath||'./llama.cpp/build/bin/llama-server'):(s.cliPath||'./llama.cpp/build/bin/llama-cli');parts.push(/\s/.test(bin)?sh(bin):bin);addSource(parts,s,warn);let skipped=LlamaCalcRules.applyDflash(parts,s,pair,filled,warn);F().forEach(f=>{if(skipped.has(f.id)||!applies(f,m)||f.special||['serverPath','cliPath','modelPath','hfRepo','hfFile','hfToken','modelUrl','dockerRepo'].includes(f.id))return;addField(parts,f,s[f.id])});appendRaw(parts,s.mtpRawFlags);appendRaw(parts,s.extraFlags);collectWarnings(s,warn);return{cmd:render(parts,s.multiline),warn}}
function addSource(p,s,w){let src=[s.modelPath,s.hfRepo,s.modelUrl,s.dockerRepo].filter(filled);if(src.length>1)w.push('Multiple model sources are filled. Priority is local path, HF repo, model URL, Docker repo.');if(filled(s.modelPath))return pair(p,'-m',s.modelPath);if(filled(s.hfRepo)){pair(p,'-hf',s.hfRepo);if(filled(s.hfFile))pair(p,'-hff',s.hfFile);if(filled(s.hfToken))pair(p,'-hft',s.hfToken);return}if(filled(s.modelUrl))return pair(p,'-mu',s.modelUrl);if(filled(s.dockerRepo))pair(p,'-dr',s.dockerRepo)}
function addField(p,f,v){if(f.type==='checkbox'){if(v)p.push(f.flag);return}if(f.map){if(f.map[v])p.push(f.map[v]);return}if(f.flag&&filled(v))pair(p,f.flag,v,f.raw)}
function pair(p,flag,v,raw=0){p.push(`${flag} ${raw?String(v).trim():sh(String(v).trim())}`)}
function appendRaw(p,t){if(!filled(t))return;String(t).split('\n').map(x=>x.trim()).filter(Boolean).forEach(x=>p.push(x))}
function collectWarnings(s,w){let has=filled(s.modelPath)||filled(s.hfRepo)||filled(s.modelUrl)||filled(s.dockerRepo)||s.listDevices||s.version||s.completionBash;if(!has)w.push('No model source selected. Add -m, -hf, -mu, or -dr unless this is intentional router-mode server usage.');if(s.mode==='server'&&s.host==='0.0.0.0'&&!filled(s.apiKey)&&!filled(s.apiKeyFile))w.push('Server is bound to 0.0.0.0 without --api-key or --api-key-file.');if(filled(s.tensorSplit)&&!/^[0-9.,\s]+$/.test(s.tensorSplit))w.push('Tensor split contains unusual characters. It should usually look like 1,1 or 3,1.');if(s.mode==='server'&&filled(s.port)){let p=parseInt(s.port,10);if(!Number.isFinite(p)||p<1||p>65535)w.push('Port must be between 1 and 65535.')}if(filled(s.extraFlags))w.push('Extra flags are appended verbatim and not validated.');if(filled(s.mtpRawFlags))w.push('Raw MTPS flags are appended verbatim and not validated.');if(filled(s.hfToken)||filled(s.apiKey))w.push('Secret fields are used in the command but are not saved to browser storage.')}
function render(p,multi){return !multi||p.length<2?p.join(' '):p[0]+' \\\n  '+p.slice(1).join(' \\\n  ')}
let logs=loadLogs();
function parseTimingIntoLogFields(){let r=parseTiming(timingPaste.value);if(!Object.keys(r).length)return toast('No timing values found.');[['logPromptTps',r.promptTps],['logGenTps',r.genTps],['logPromptTokens',r.promptTokens],['logGenTokens',r.genTokens],['logTotalMs',r.totalMs]].forEach(([id,v])=>{if(filled(v))$(id).value=v});toast('Timing output parsed.')}
function parseTiming(t){let r={},s=String(t||''),j=parseJSONTiming(s);if(j)Object.assign(r,j);let pm=s.match(/prompt eval time\s*=\s*([\d.]+)\s*ms\s*\/\s*(\d+)\s*tokens?.*?\(([\d.]+)\s*tokens per second\)/i),em=s.match(/eval time\s*=\s*([\d.]+)\s*ms\s*\/\s*(\d+)\s*(?:runs?|tokens?).*?\(([\d.]+)\s*tokens per second\)/i),tm=s.match(/total time\s*=\s*([\d.]+)\s*ms/i);if(pm){r.promptTokens=pm[2];r.promptTps=pm[3]}if(em){r.genTokens=em[2];r.genTps=em[3]}if(tm)r.totalMs=tm[1];return r}
function parseJSONTiming(t){let a=[t.trim()],i=t.indexOf('{'),j=t.lastIndexOf('}');if(i>=0&&j>i)a.push(t.slice(i,j+1));for(let c of a){try{let o=JSON.parse(c),x=findTiming(o);if(!x)continue;let r={};if(x.prompt_per_second!==undefined)r.promptTps=round(x.prompt_per_second);if(x.predicted_per_second!==undefined)r.genTps=round(x.predicted_per_second);if(x.prompt_n!==undefined)r.promptTokens=x.prompt_n;if(x.predicted_n!==undefined)r.genTokens=x.predicted_n;if(x.prompt_ms!==undefined&&x.predicted_ms!==undefined)r.totalMs=round(Number(x.prompt_ms)+Number(x.predicted_ms));return r}catch{}}}
function findTiming(v){if(!v||typeof v!=='object')return null;if(v.timings)return v.timings;if(Array.isArray(v)){for(let x of v){let y=findTiming(x);if(y)return y}}else for(let k of Object.keys(v)){let y=findTiming(v[k]);if(y)return y}return null}
function logRun(){let s=state(),e={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),timestamp:new Date().toISOString(),mode:s.mode,name:logName.value.trim()||guessName(s),model:s.modelPath||s.hfRepo||s.modelUrl||s.dockerRepo||'',context:s.ctxSize||'',promptTps:logPromptTps.value.trim(),genTps:logGenTps.value.trim(),promptTokens:logPromptTokens.value.trim(),genTokens:logGenTokens.value.trim(),totalMs:logTotalMs.value.trim(),build:logBuild.value.trim(),notes:logNotes.value.trim(),command:build().cmd};logs.unshift(e);saveLogs();renderLogs();toast('Run logged.')}
function renderLogs(){if(!logs.length){logTable.innerHTML='<tr><td colspan="8" style="color: var(--muted);">No benchmark logs yet.</td></tr>';return}logTable.innerHTML=logs.map(e=>`<tr><td>${esc(new Date(e.timestamp).toLocaleString())}</td><td><strong>${esc(e.name)}</strong><div class="field-help">${esc(e.model)}</div></td><td>${esc(e.mode)}</td><td>${esc(e.promptTps)}</td><td>${esc(e.genTps)}</td><td>${esc([e.promptTokens,e.genTokens].filter(Boolean).join(' / '))}</td><td>${esc(e.build)}</td><td><div class="row-actions"><button class="copy-button" data-copy="${e.id}">Copy Command</button><button class="danger-button" data-del="${e.id}">Delete</button></div></td></tr>`).join('');document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copyText(logs.find(x=>x.id===b.dataset.copy)?.command||'','Logged command copied.'));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{logs=logs.filter(x=>x.id!==b.dataset.del);saveLogs();renderLogs()})}
function guessName(s){let x=s.modelPath||s.hfRepo||s.modelUrl||s.dockerRepo||'llama.cpp run';return x.split('/').pop()||x}
function logsMarkdown(){let a=['| Date | Name | Mode | Prompt t/s | Gen t/s | Tokens | Build | Notes | Command |','|---|---|---|---|---|---|---|---|---|'];logs.forEach(l=>a.push(`| ${md(l.timestamp)} | ${md(l.name)} | ${md(l.mode)} | ${md(l.promptTps)} | ${md(l.genTps)} | ${md([l.promptTokens,l.genTokens].filter(Boolean).join(' / '))} | ${md(l.build)} | ${md(l.notes)} | \`${md(l.command)}\` |`));return a.join('\n')}
function logsCsv(){let rows=[['timestamp','name','mode','model','context','prompt_tps','gen_tps','prompt_tokens','gen_tokens','total_ms','build','notes','command']];logs.forEach(l=>rows.push([l.timestamp,l.name,l.mode,l.model,l.context,l.promptTps,l.genTps,l.promptTokens,l.genTokens,l.totalMs,l.build,l.notes,l.command]));return rows.map(r=>r.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n')}
function loadLogs(){try{return JSON.parse(localStorage.getItem(S_LOGS))||[]}catch{return []}}function saveLogs(){localStorage.setItem(S_LOGS,JSON.stringify(logs))}
function clearLogs(){if(!confirm('Clear all benchmark logs?'))return;logs=[];saveLogs();renderLogs();toast('Logs cleared.')}function resetBuilder(){if(!confirm('Reset builder state? Benchmark logs stay untouched.'))return;localStorage.removeItem(S_STATE);location.reload()}
function copyText(t,m){navigator.clipboard.writeText(t).then(()=>toast(m))}function toast(m){let d=document.createElement('div');d.className='app-toast app-toast--visible';d.textContent=m;$('toast-container').appendChild(d);setTimeout(()=>{d.classList.remove('app-toast--visible');setTimeout(()=>d.remove(),240)},2400)}
function md(v){return String(v??'').replace(/\|/g,'\\|').replace(/\n/g,'<br>')}function round(v){let n=Number(v);return Number.isFinite(n)?String(Math.round(n*100)/100):String(v)}
renderBuilder();applyState();addEvents();updateAll();renderLogs();
